kind: pipeline
type: docker
name: image builder 

steps:
  - name: publish
    image: plugins/ecr 
    settings: 
        registry:
           from_secret: MLF_REGISTRY
        repo:
           from_secret: MLF_REPO
        region:
           from_secret: REGION
        tags:
          - latest
          - ${DRONE_TAG}
trigger:
  branch:
  - master
  event:
  - tag
